[en]
section-newsale="New sale"
section-about="About"
section-sellers="Sellers"
name="Name"
stand_number="Stand number"
code="Code"

[gl]
section-newsale="Nova venta"
section-about="Acerca de"
section-sellers="Casetas"
name="Nome"
stand_number="Nº Caseta"
code="Código"

[es]
section-newsale="Nueva venta"
section-about="Acerca de"
section-sellers="Casetas"
name="Nombre"
stand_number="Nº Caseta"
code="Código"